### PR TITLE
chore: fix script cannot find minid

### PR DESCRIPTION
**Pull request by blavejr**
Hi guys, so I was trying this out and ran into an issue where minid was not found as described here: https://github.com/cosmosregistry/chain-minimal/issues/123

After some frustrations and a little digging I after install go was placing minid in a different directory from the one the script expected, as this might be a little frustrating for newbies such as myself I decided to add a little something to make the script try and find the minid executable dynamically.

I hope this is a good idea if not please do correct me but after this my install works flawlessly.

### CODE REVIEW

**Comment by julienrbrt** [comment]
The script does expect a correct path configuration.
I agree that we should check if MINID variable isn't empty / that the binary exists, but we shouldn't add go logic in there.

**Comment by blavejr** [comment]
We could create a second script to try and detect where minid was placed after install and maybe give some steps as to how to rectify the issue, its a small hurdle but for a nood its pretty frustrating.

or any other resolution, I am happy to implement any idea and make a PR

**Comment by julienrbrt** [comment]
This repo should be kept minimal, imho adding another script isn't really necessary.
Displaying an error that minid is not found should be enough for the user to figure out what's wrong.

**Comment by blavejr** [comment]
Cool @julienrbrt I'll make a pr

**Comment by julienrbrt** [comment]
Thank you! I have done something similar in https://github.com/cosmosregistry/chain-minimal/commit/da660cd8b5926bc377e998e04e51c07ad9a16df4.

**Pull request closed without merging**
